name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Adjust to your required Node.js version

    - name: Install dependencies
      run: npm install
      working-directory: src/react-app

    - name: Build React app
      run: npm run build
      working-directory: src/react-app

    - name: Start React app
      run: |
        nohup npx http-server src/react-app/build -p 8080 &
        sleep 10  # Wait for server to start
        curl -I http://localhost:8080 | grep "200 OK"
      working-directory: src/react-app

    - name: Install Electron dependencies
      run: npm install --save-dev electron
      working-directory: .

    - name: Start Electron app
      run: |
        npm start &
        sleep 10  # Wait for Electron to start
        # Example command to check if Electron is running, adjust as needed
        curl -I http://localhost:8080 | grep "200 OK" || true
      working-directory: .

    - name: Kill all processes
      run: |
        pkill -f http-server || true
        pkill -f electron || true
      working-directory: .